### PR TITLE
Synthesis Panel Updates

### PR DESCRIPTION
**Pull request by N151343**

### CODE REVIEW

**Comment by rkprad** [comment]
@N151343 

image

If you look above ,the size inside text box between number and character is different. 

* 
image

Scroll bar is still showing up. 

* 
image

Switch the position of the buttons; First Remove and then Generate. 
For Generate Four-Bar. Move Four-Bar to the second line. That way, it will appear as a single word. 

* 
image
 
Make sure the buttons are of the same width. 

* 
image

May be push the synthesis a bit. Make sure this spacing is consistent across all three panels.

**Comment by rkprad** [comment]
@N151343 

Increase the gap between buttons and the next drop down: 
image

image

**Comment by N151343** [comment]
I've committed some changes, can you review them?

**Review by rkprad — COMMENTED** [review]
Reviewed and all good

**Pull request merged**
